/*
BigInt is a special numeric type that provides support for integers of random length.

A BigInt is generated by appending n to the end of an integer literal or by calling the function BigInt that generates BigInt from strings, numbers, etc.
*/


// Example1:
//const bigintvar = 31313211321321321311121111n;
// OR
// const bigintvar = BigInt("4789654137539517539512587413690");

// const bigintFromNumber = BigInt(10);// same as 10n

/* common math operations can be done on BigInt as regular numbers. But BigInt and regular numbers cannot be mixed in the expression. */

//Example:
// alert(3n + 2n);// 5
// alert(7n + 2n);//3
// alert(8n + 2);//Error: cannot mix BigInt and other types

/* Here the division returns the result rounded towards zero, without the decimal part. Thus, all operations on BigInt return BigInt.

 */


/* BigInt and regular numbers must be explicitly converted using either BigInt() or Number(), as shown below:  
*/
//Example:
let bigintvar = 6n;
let numvar = 3;

// number to bigint 
alert(bigintvar + BigInt(numvar));// 9

// bigint to number
alert(Number(bigintvar )+ numvar); //9

/* In the above example, if the bigintvar is too large that it won’t fit the number type, then extra bits will be cut off. */